Дано: списки a,b=[1,1,1],[3,3,3]

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [4]:
import numpy as np

a,b=[1,1,1],[3,3,3]

A = np.array(a)
B = np.array(b)

print(-((B-A)*(B/2)))


[3. 3. 3.]


Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:

[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]


In [12]:
import numpy as np

chees = np.zeros((8,8))

chess[0, :] = [-4, -3, -2, -6, -5, -2, -3, -4]
chess[1, :] = -1
chess[6, :] = 1
chess[7, :] = [4, 3, 2, 6, 5, 2, 3, 4]

print(chees_desk)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [21]:
import numpy as np

number = np.arange(2,21,2)
odd_number = number + 1
multi = number*odd_number

print(number)
print(odd_number)
print(multi)

[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[  6  20  42  72 110 156 210 272 342 420]


Имеется массив my_array

my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])

Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [30]:
my_array = np.array([[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20],
                    [21,22,23,24,25]])

print(my_array[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [33]:
my_sin = np.sin(my_array)

summ_array = np.sum(my_sin)

print(my_sin)

print()
print()

print(round(summ_array,3))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]


-0.058


Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [16]:
x = great_array.reshape(-1)
print(x[150])

5.313292845913055


Получить индексы, для которых элементы массивов A и B совпадают.
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
Ожидается результат:
array([1, 3, 5, 7])

In [14]:
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
C = np.where(A==B)
print(C)

(array([1, 3, 5, 7]),)
